```{r}
library(tidyverse)
library(dbplyr)
library(palmerpenguins)
library(matrixStats)

matrix <- read.table("~/qb25-answers/week6/read_matrix.tsv") 
matrix <- as.matrix(matrix)
valid_matrix = matrix[complete.cases(matrix),]
row_sd= rowSds(valid_matrix)
sorted_matrix <- valid_matrix[order(row_sd),] #get from googling 
n500_matrix <- sorted_matrix[1:500,]

```

```{r}
n500_matrix <- t(n500_matrix)
variable_pca_result= prcomp(n500_matrix)
summary(variable_pca_result)
variance <- variable_pca_result$sdev
```

```{r}
norm_n500 =scale(n500_matrix)
colMeans(norm_n500)

PCA_plotting_df <- tibble(PC1=variable_pca_result$x[,1],PC2=variable_pca_result$x[,2], Sample= rownames(n500_matrix))

PCA_summary <- tibble(PC =seq(1, nrow(norm_n500),1), sd= variable_pca_result$sdev) %>%
    mutate(var=sd^2) %>%
  mutate(norm_variance= var/sum(var))

library(ggplot2)
PCA_plotting_df %>%
  mutate(Sample = rownames(n500_matrix))
colnames(PCA_plotting_df) <- c("PC1", "PC2", "Sample")
PCA_plotting_df <- PCA_plotting_df %>%
  tidyr::separate(Sample, into = c("Tissue", "Replicate"), sep = "_")

PCA_plotting_df <- PCA_plotting_df %>%
  mutate(Tissue = dplyr::recode(Tissue,
                         "A1" = "anterior 1",
                         "A2.3" = "anterior 2, 3",
                         "Cu" = "Copper",
                         "LFC.Fe" = "large flat cell, iron",
                         "Fe" = "iron",
                         "P1" = "posterior 1",
                         "P2.4" = "posterior 2, 4"))
PCA_plot <-ggplot(PCA_plotting_df, aes(x = PC1, y = PC2, color = Tissue, shape = Replicate)) +
  geom_point(size = 3) +
  labs(
    title = "PCA of Top 500 Variable Genes",
    x ="PC1",
    y = "PC2"
  ) 

print(PCA_plot)

ggsave("~/qb25-answers/week6/Exercise_1_PCA_plot.png")

PCA_summary %>% ggplot(aes(PC,norm_variance))+
geom_bar(stat = "identity")+
labs(title = "Variance Explained by Each Principal Component",
       x = "Principal Component",
       y = "Proportion of Variance Explained")
ggsave("~/qb25-answers/week6/Exercise_1_variance_barchart.png")
```

```{r}
combined_df = n500_matrix[seq(1, 21, 3),]
combined_df= combined_df + n500_matrix[seq(2, 21, 3),]
combined_df = combined_df + n500_matrix[seq(3, 21, 3),]
combined_df = combined_df / 3
combined_df= t(combined_df)

gene_sd <- rowSds(combined_df, na.rm = TRUE)
filtered_combined <- combined_df[gene_sd > 1, ]

set.seed(42)
kmeans_results <- kmeans(scale(as.matrix(combined_df)), centers = 12, nstart = 100)

ordering = order(kmeans_results$cluster)
data_ordered <- combined_df[ordering, ]

heatmap <-heatmap(as.matrix(data_ordered), Rowv=NA, Colv=NA,
        RowSideColors=RColorBrewer::brewer.pal(12, name="Paired")[kmeans_results$cluster[ordering]], scale='none')

print(heatmap)

ggsave("~/qb25-answers/week6/heatmap.png")

```
```{r}
cluster_4_genes <- rownames(combined_df)[kmeans_results$cluster == 4]
cluster_6_genes <- rownames(combined_df)[kmeans_results$cluster == 6]
print(cluster_4_genes)
print(cluster_6_genes)
write.table(cluster_4_genes, "cluster4_genes.txt", quote = FALSE, row.names = FALSE, col.names = FALSE)
write.table(cluster_6_genes, "cluster6_genes.txt", quote = FALSE, row.names = FALSE, col.names = FALSE)

```
FBgn0266917,FBgn0030269,FBgn0038593,FBgn0039601,FBgn0030055,FBgn0031114,FBgn0034946,FBgn0283510,FBgn0020018,FBgn0029594,FBgn0036305,FBgn0031224,FBgn0026080,FBgn0034269,FBgn0031054,FBgn0031003,FBgn0264691,FBgn0051852,FBgn0032243,FBgn0032030,FBgn0046222,FBgn0014269,FBgn0037117,FBgn0030342,FBgn0036915,FBgn0022027,FBgn0037901,FBgn0019932,FBgn0023081,FBgn0031909,FBgn0034763,FBgn0023509,FBgn0034793,FBgn0036911,FBgn0265574,FBgn0010417,FBgn0003742,FBgn0266667,FBgn0036052,FBgn0022987,FBgn0037852,FBgn0034242,FBgn0039712,FBgn0031871,FBgn0034537,FBgn0038462,FBgn0086785,FBgn0037255,FBgn0038546,FBgn0033376,FBgn0011290,FBgn0028965,FBgn0033859,FBgn0029929,FBgn0034982,FBgn0015828,FBgn0039116,FBgn0000482,FBgn0010750,FBgn0035769,FBgn0037621,FBgn0034727,FBgn0023512,FBgn0031043,FBgn0033609,FBgn0032348,FBgn0052221,FBgn0086446,FBgn0053158,FBgn0035703,FBgn0051301,FBgn0038146







